name: "CI Tests"

on:
  - "pull_request"
  - "push"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0"]

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v2"
        with:
          node-version: "14"
      - uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: yarn install
      - run: yarn build
      - run: bin/rails test test/**/*_test.rb

      - name: Fail when generated changes are not checked-in
        run: |
          git update-index --refresh
          git diff-index --quiet HEAD --
